require('dotenv')
	.config();


const Secrets = {
	PORT: process.env.PORT || 4000,
	HOST: process.env.HOST || "localhost",
	ENVIRONMENT: process.env.NODE_ENV || "local",
	DATABASE_LOCAL_URL: process.env.DATABASE_LOCAL_URL,
	DATABASE_LIVE_URL: process.env.DATABASE_LIVE_URL,
	DATABASE_NAME: process.env.DATABASE_NAME,
	JWT_TOKEN: process.env.JWT_TOKEN,
	OPENAI_KEY: process.env.OPENAI_KEY,
	MAILER_API_KEY: process.env.MAILER_API_KEY,
	MAILER_DOMAIN: process.env.MAILER_DOMAIN,
	SENDGRID_KEY: process.env.SENDGRID_KEY,
	LOCAL_BASE_URL: process.env.LOCAL_BASE_URL,
	WEB_STAGING_URL: process.env.WEB_STAGING_URL,
	WEB_PRODUCTION_URL: process.env.WEB_PRODUCTION_URL,
	EMAIL_USERNAME: process.env.EMAIL_USERNAME,
	EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
	STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
	STRIPE_PUBLIC_KEY: process.env.STRIPE_PUBLIC_KEY,
	STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
	STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
	STRIPE_PRICE_ID: process.env.STRIPE_PRICE_ID,
	CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
	CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
	CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
	USER_TYPE: process.env.USER_TYPE,
	DAFAULT_PASSWORD: process.env.DAFAULT_PASSWORD,
	LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID,
	LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET,
	LINKEDIN_AUTH_URL: process.env.LINKEDIN_AUTH_URL,
	LINKEDIN_ACCESS_TOKEN_URL: process.env.LINKEDIN_ACCESS_TOKEN_URL,
	LINKEDIN_REDIRECT_URL: process.env.LINKEDIN_REDIRECT_URL,
	LINKEDIN_SCOPE: process.env.LINKEDIN_SCOPE

}

module.exports = Secrets;